model:
  n_layers: 6
  hidden_size: 384
  n_heads: 6
  head_dim: 64
  ffn_size: 1536
  vocab_size: 32000
  max_seq_len: 2048

training:
  batch_size: 10
  seq_len: 1024
  learning_rate: 1e-4
  num_epochs: 10
  warmup_steps: 1000
  weight_decay: 0.01

output:
  save_path: "models/llama_model.pt" 